package pt.isec.pd.comum.enumeracoes;

public enum Tipomensagemenum {
    LOGIN,
    LOGOUT,
    USER_REGISTO,
    USER_EDITA_INFORMACAO,
    USER_CRIA_GRUPO,
    USER_INSERIDO_NO_GRUPO,
    USER_CRIA_CONVITE,
    USER_LISTA_GRUPOS,
    USER_EDITA_GRUPO,
    USER_ELIMINA_GRUPO,
    USER_SAI_GRUPO,
    USER_LISTA_CONVITES,
    USER_DECIDE_CONVITE,
    USER_INSERE_DESPESA,

    USER_INSERE_PAGAMENTO,
    USER_VISUALIZA_GASTOS,
    USER_HISTORICO_DESPESAS,
    USER_EXPORTA_HISTORICO_CSV_FICHEIRO,
    USER_EDITA_DESPESA,
    USER_ELIMINA_DESPESA,
    USER_LISTA_PAGAMENTOS,
    USER_ELIMINA_PAGAMENTO_EFECTUADO,
    USER_VISUALIZACAO_DOS_SALDOS,
}
